apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ee8egmcdc-go 
  janus-idp.io/tekton: ee8egmcdc-go
  backstage.io/kubernetes-id: ee8egmcdc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ee8egmcdc-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  